### ISSUE TITLE
Create LICENSE.txt file

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/proethos#71]
The following text must be part of LICENSE.txt file:

PROETHOS

License

NOTICE TO USER:  Please read this Software License carefully.  By using all or any portion of this Software, you accept all the terms and conditions of this License, and recognize that this License is as enforceable as any written negotiated document signed by you.

The Pan American Health Organization and its affiliates (“PAHO”) hold all intellectual property rights in the PROETHOS Software.  By means of this License PAHO will grant you permission to use the Software only in accordance with the terms and conditions set forth herein. 

1. Software License. As long as you comply with the terms and conditions of this License, PAHO grants you a non-exclusive, royalty-free, transferable license to use, reproduce, modify and distribute the Software as further set forth below in the understanding that the Software will be used solely for non-commercial purposes.

1. Intellectual Property Ownership, Copyright Protection.  Copyright of the Software belongs to PAHO.  All rights not expressly granted herein are reserved by PAHO.

1. Trademark, Name and Logo. The trademarks, names and logos, included in the Software, are the property of PAHO.  You are not permitted to use or reproduce them, without the prior express written consent of PAHO other than as permitted by the Software. Software may not be used to promote licensees activities, products or services.

1. Notices.  PAHO copyrights shall be acknowledged with a reference in the Software and  any printed materials or electronic documentation accompanying the use of the software, as follows:
 * PROETHOS © Pan American Health Organization, 2013. 

1. Copies. You may convey unmodified copies of the Software’s source code as you receive it, in any medium, provided that you distribute it under the terms of this License and that you conspicuously on each copy:

 a. Include the copyright notice referred above, 
 b. Include the text of this License,
 c. Keep intact all notices of the absence of any warranty, and
 d. Include the prohibitions on of commercial use of the Software and the promotion of licensee’s activities, products or services. 

1. Each time a copy of the Software is distributed the recipient automatically receives a license from PAHO subject to these same terms and conditions.

1. Modifications.  You may perform structural modifications of this Software, provided that you meet these conditions:

 a. The modified version of the Software must carry prominent notices stating that you modified the Software,
 b. The modified version must be released under this License, and
 c. You shall maintain all system credits and refrain from using the software for commercial purposes.

1. Updates.  Any and all Updates, if provided, are done so on the same basis as the original Software License unless otherwise indicated in writing by PAHO.  PAHO reserves the right to provide Updates to this Software on amended terms as it sees fit. User shall be responsible for installing the latest version of the software. 

1. Disclaimer.  PAHO disclaims any and all implied warranties or conditions, including any implied warranty of title, non-infringement, merchantability or fitness for a particular purpose.  The information contained within the Software is provided in good faith and every care has been taken in its preparation.  PAHO does not and cannot warrant the performance or results you may obtain by using the Software. PAHO provides no warranties, nor does it assume any legal liability or responsibility for the accuracy, completeness or usefulness of any of the information supplied.  Unless expressed herein, no condition, warranty or representation by PAHO is given and shall not be implied in relation to the Software available for downloading.  The disclaimer of responsibility applies to any failure of performance, error, omission, interruption, deletion, defect, delay in operation or transmission, computer virus, communication line failure, theft or destruction.

1. Limitation of Liability.  In no event will PAHO be responsible to you for any damages, claims or costs whatsoever, or any consequential indirect or incidental damages or any lost profits or lost savings, even if a PAHO representative has been advised of the possibility of such loss, damages, claims or costs. Furthermore PAHO will not be responsible for any claim by any third party arising out of use or inability to use the Software.

1. Privileges and Immunities. Nothing contained in this License shall be deemed a waiver, express or implied, of any immunity from suit, judicial process, confiscation, taxation, or other immunity or privilege which PAHO may enjoy, whether pursuant to treaty, convention, law, order or decree of an international or national character or otherwise, or in accordance with international customary law.

1. Resolution of Disputes.  You and PAHO shall use their best efforts to settle amicably any dispute, controversy or claim arising out of, or relating to this License.  Unless any such dispute, controversy or claim between the parties arising out of or relating to this Licensee or breach, termination or invalidity thereof is settled amicably within sixty (60) days after receipt by one Party of the other party’s request for such amicable settlement, such dispute, controversy or claim shall be referred by either party to arbitration in accordance with the UNCITRAL Arbitration Rules then obtaining.  The arbitral tribunal shall have no authority to award punitive damages.  Any arbitration award rendered as a result of such arbitration shall be considered to be the final adjudication of any such controversy, claim or dispute and shall bind the Parties.

1. Severability.  Any provision of this License prohibited by the laws of any jurisdiction shall, as to such jurisdiction, be ineffective to the extent of such prohibition, without invalidating the remaining provisions of this License.

1. Termination for cause.  This License will commence on the date of first use and unless terminated in accordance with the terms hereof, will continue in effect indefinitely.  PAHO has the right to terminate this License if, after thirty (30) days notice to Licensee, any of the following conditions has not been cured by Licensee:

 (i) Licensee Uses or permits the Software or its updates to be used, in any manner or for any purpose not authorized hereunder; or
 (ii) Licensee is otherwise in breach of this License in any material respect.

**Comment by asael-silva** [comment]
According to Mrs. Carla's orientation, follows the LICENSE.txt reviewed with 'ProEthos' normalized:

ProEthos

License

NOTICE TO USER: Please read this Software License carefully. By using all or any portion of this Software, you accept all the terms and conditions of this License, and recognize that this License is as enforceable as any written negotiated document signed by you.

The Pan American Health Organization and its affiliates (“PAHO”) hold all intellectual property rights in the ProEthos Software. By means of this License PAHO will grant you permission to use the Software only in accordance with the terms and conditions set forth herein.

Software License. As long as you comply with the terms and conditions of this License, PAHO grants you a non-exclusive, royalty-free, transferable license to use, reproduce, modify and distribute the Software as further set forth below in the understanding that the Software will be used solely for non-commercial purposes.

Intellectual Property Ownership, Copyright Protection. Copyright of the Software belongs to PAHO. All rights not expressly granted herein are reserved by PAHO.

Trademark, Name and Logo. The trademarks, names and logos, included in the Software, are the property of PAHO. You are not permitted to use or reproduce them, without the prior express written consent of PAHO other than as permitted by the Software. Software may not be used to promote licensees activities, products or services.

Notices. PAHO copyrights shall be acknowledged with a reference in the Software and any printed materials or electronic documentation accompanying the use of the software, as follows:

ProEthos © Pan American Health Organization, 2013.
Copies. You may convey unmodified copies of the Software’s source code as you receive it, in any medium, provided that you distribute it under the terms of this License and that you conspicuously on each copy:

a. Include the copyright notice referred above, 
b. Include the text of this License,
c. Keep intact all notices of the absence of any warranty, and
d. Include the prohibitions on of commercial use of the Software and the promotion of licensee’s activities, products or services.

Each time a copy of the Software is distributed the recipient automatically receives a license from PAHO subject to these same terms and conditions.

Modifications. You may perform structural modifications of this Software, provided that you meet these conditions:

a. The modified version of the Software must carry prominent notices stating that you modified the Software,
b. The modified version must be released under this License, and
c. You shall maintain all system credits and refrain from using the software for commercial purposes.

Updates. Any and all Updates, if provided, are done so on the same basis as the original Software License unless otherwise indicated in writing by PAHO. PAHO reserves the right to provide Updates to this Software on amended terms as it sees fit. User shall be responsible for installing the latest version of the software.

Disclaimer. PAHO disclaims any and all implied warranties or conditions, including any implied warranty of title, non-infringement, merchantability or fitness for a particular purpose. The information contained within the Software is provided in good faith and every care has been taken in its preparation. PAHO does not and cannot warrant the performance or results you may obtain by using the Software. PAHO provides no warranties, nor does it assume any legal liability or responsibility for the accuracy, completeness or usefulness of any of the information supplied. Unless expressed herein, no condition, warranty or representation by PAHO is given and shall not be implied in relation to the Software available for downloading. The disclaimer of responsibility applies to any failure of performance, error, omission, interruption, deletion, defect, delay in operation or transmission, computer virus, communication line failure, theft or destruction.

Limitation of Liability. In no event will PAHO be responsible to you for any damages, claims or costs whatsoever, or any consequential indirect or incidental damages or any lost profits or lost savings, even if a PAHO representative has been advised of the possibility of such loss, damages, claims or costs. Furthermore PAHO will not be responsible for any claim by any third party arising out of use or inability to use the Software.

Privileges and Immunities. Nothing contained in this License shall be deemed a waiver, express or implied, of any immunity from suit, judicial process, confiscation, taxation, or other immunity or privilege which PAHO may enjoy, whether pursuant to treaty, convention, law, order or decree of an international or national character or otherwise, or in accordance with international customary law.

Resolution of Disputes. You and PAHO shall use their best efforts to settle amicably any dispute, controversy or claim arising out of, or relating to this License. Unless any such dispute, controversy or claim between the parties arising out of or relating to this Licensee or breach, termination or invalidity thereof is settled amicably within sixty (60) days after receipt by one Party of the other party’s request for such amicable settlement, such dispute, controversy or claim shall be referred by either party to arbitration in accordance with the UNCITRAL Arbitration Rules then obtaining. The arbitral tribunal shall have no authority to award punitive damages. Any arbitration award rendered as a result of such arbitration shall be considered to be the final adjudication of any such controversy, claim or dispute and shall bind the Parties.

Severability. Any provision of this License prohibited by the laws of any jurisdiction shall, as to such jurisdiction, be ineffective to the extent of such prohibition, without invalidating the remaining provisions of this License.

Termination for cause. This License will commence on the date of first use and unless terminated in accordance with the terms hereof, will continue in effect indefinitely. PAHO has the right to terminate this License if, after thirty (30) days notice to Licensee, any of the following conditions has not been cured by Licensee:

(i) Licensee Uses or permits the Software or its updates to be used, in any manner or for any purpose not authorized hereunder; or
(ii) Licensee is otherwise in breach of this License in any material respect.

**Comment by asael-silva** [comment]
Collecting information on licenses from third-party libraries in use.

**Comment by renatomurasaki** [comment]
According to PAHO LEG advice, we must include a new clause on ProEthos license in order to clarify the use of third-party libraries as follows:

"Open Source Software: Certain components of the Proethos Software may be subject to a license that permits end users to modify these portions and redistribute its modifications (“Open Source software”). Use, modification and redistribution of the Open Source software is governed solely by the terms and conditions of the applicable Open Source License. A list of the Open Source Softwares and the applicable Open Source licenses including relevant code can be obtained at https://github.com/bireme/proethos/xxxxx.txt"

xxxxx.txt will have the list of Open Source Softwares and related license.

This new clause will be the ninth one, after Updates clause and followed by (10) Disclaimer, (11) Limitation of Liability, (12) Privileges and Immunities, (13) Resolution of Disputes, (14) Severability y (15) Termination for cause.

**Comment by asael-silva** [comment]
License files LICENSE.txt, COPYRIGHT.txt and README.txt were added to the project. README.md was changed to display the same contents of README.txt.

**Comment by asael-silva** [comment]
Files published this date.
